name: BookTrackerDeploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: BookTracker
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Install dependencies
      run: dotnet build Booktracker/BookTracker.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
  unittests:
    needs: build
    name:  Unit Testing
    runs-on: windows-latest
    steps: 
#        - run: dotnet test BookTracker\BookTracker\BookTrackerTest\BookTrackerTest.csproj --no-build --verbosity normal
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Install dependencies
      run: dotnet restore
    - name: Unit Tests
      run: dotnet test SpiceTheWorld.Tests --no-restore --verbosity Minimal
      
      
#       with:
#         dotnet-version: ${{ matrix.dotnet-version }}
#     - name: Install dependencies
#       run: dotnet restore
#     - name: Build
#       run: dotnet build --configuration Release --no-restore
      
#   unittests:      
#     needs: build
#     name:  Unit Testing
#     runs-on: windows-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
#       uses: actions/setup-dotnet@v1.7.2
#       with:
#         dotnet-version: ${{ matrix.dotnet-version }}
#     - name: Install dependencies
#       run: dotnet restore
#     - name: Unit Tests
#       run: dotnet test SpiceTheWorld.Tests --no-restore --verbosity Minimal          
 
#   regression:  
#     needs: unittests 
#     name: Regression
#     runs-on: windows-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
#       uses: actions/setup-dotnet@v1.7.2
#       with:
#         dotnet-version: ${{ matrix.dotnet-version }}
#     - name: Install dependencies
#       run: dotnet restore
#     - name: Regression tests 
#       run: dotnet test SpiceTheWorld.Regression --no-restore --verbosity Minimal --filter TestCategory=SpiceRegression

# enter image description here
