name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore App
      run: dotnet build BookTracker/BookTracker.sln
    - name: Build App
      run: dotnet build BookTracker/BookTracker/BookTracker.sln --configuration Release --no-restore
    - name: Test App
      run: dotnet test BookTracker\BookTracker\BookTrackerTest\BookTrackerTest.csproj --no-build --verbosity normal
